repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: lint
        name: Run linting
        entry: bash -c 'poetry run ./scripts/lint.sh'
        language: system
        pass_filenames: false
        types: [python]
        require_serial: true
