services:
  agent:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../..:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
