services:
  app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    volumes:
      - ../../src:/app/src
      - ../../pyproject.toml:/app/pyproject.toml
      - ../../README.md:/app/README.md
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - prometheus

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
volumes:
  redis_data:
